name: NycuRO-Core
main: nycuro.Core
version: "1.0"
api: ["1.0.0"]
author: NycuRO
description: NycuRO-Core

commands:
  spawn:
    description: Teleport to Spawn
    usage: "/spawn"
    permission: core.spawn
  shop:
    description: Shop, Sell, Trade in one command
    usage: "/shop"
    permission: core.shop
    permission: core.warps
  kit:
    description: Choise Kit
    usage: "/kit"
    permission: core.kit
  kits:
    description: List Kits
    usage: "/kits"
    permission: core.kits
  utils:
    description: List of Utils
    usage: "/utils"
    permission: core.utils
  spawnboss:
    description: SpawnBoss
    usage: "/spawnboss"
    permission: core.spawnboss
  droppartymessage:
    description: DropPartyMessage
    usage: "/droppartymessage"
    permission: core.droppartymessage
  spawnentities:
    description: SpawnEntities
    usage: "/spawnentities"
    permission: core.spawnentities
  servers:
    description: Show Servers
    usage: "/servers"
    permission: core.servers

permissions:
  core.spawn:
    description: "Teleport to Spawn!"
    default: true
  core.shop:
    description: "Shop, Sell, Trade in one command!"
    default: true
  core.kit:
    description: "Choise Kit"
    default: true
  core.kits:
    description: "List Kits"
    default: true
  core.utils:
    description: "List of Utils"
    default: true
  core.spawnboss:
    description: "SpawnBoss"
    default: op
  core.droppartymessage:
    description: "DropPartyMessage"
    default: op
  core.spawnentities:
    description: "Spawn Entities"
    default: op
  core.servers:
    description: "Show Servers"
    default: true